### ISSUE TITLE
"wopr -r generate" results in segmentation fault

### ISSUE THREAD

**Issue by matjemeisje** [LanguageMachines/wopr#2]
I installed wopr and all its dependencies today, all cloned from their master branches on github (OS: Linux Mint 18.1). Using the attached file (generated with ucto) I did the following:

`wopr -r lexicon -p filename:HRH-HS.txt`
`wopr -r window_lr -p filename:HRH-HS.txt,lc:2,rc:0`
`wopr -l -r make_ibase -p filename:HRH-HS.txt.l2r0`
`wopr -r generate -p ibasefile:HRH-HS.txt.l2r0.ibase,filename:out1,ws:2`

The first three commands finish without problems, the last command does not:

`17:52:26.42: Starting wopr 1.40.5`
`17:52:26.42: Timbl support built in.`
`17:52:26.42: Based on timbl 6.4.9`
`17:52:26.42: Based on libfolia 1.6.1`
`17:52:26.42: ICU support, version 55.1`
`17:52:26.42: std::numeric_limits<int>::max() = 2147483647`
`17:52:26.42: std::numeric_limits<long>::max() = 9223372036854775807`
`17:52:26.42: PID:  26946 PPID:  13999`
`17:52:26.42: Running: generate`
`17:52:26.42: generate`
`17:52:26.42:  filename:   out1`
`17:52:26.42:  ibasefile:  HRH-HS.txt.l2r0.ibase`
`17:52:26.42:  timbl:      `
`17:52:26.42:  ws:         2`
`17:52:26.42:  mode:       1`
`17:52:26.42:  end:        .`
`17:52:26.42:  n:          10`
`17:52:26.42:  len:        50`
`17:52:26.42:  sc:         false`
`17:52:26.42:  lowercase:  false`
`17:52:26.42:  OUTPUT:     out1.gen`
`Reading Instance-Base from: HRH-HS.txt.l2r0.ibase`

`Size of InstanceBase = 281273 Nodes, (11250920 bytes), 26.60 % compression`
`Feature Permutation based on Data File Ordering :`
`< 2, 1 >`
`17:52:26.92: Instance base loaded.`
`Segmentation fault`

[HRH-HS.txt](https://github.com/LanguageMachines/wopr/files/788067/HRH-HS.txt)

**Comment by kosloot** [comment]
Ok, dat gaat idd mis.
Moet onderzocht worden

**Comment by kosloot** [comment]
Ok. De fout zit in:
const std::string& Config::get_value( const std::string& k, const std::string& d ) ...
Als je als tweede parameter een string constante meegeeft, dan bestaat die slechts tot het einde fan de functie. Bijv: 
 const std::string& start            = c.get_value( "start", "" );
De variabele 'start' wordt geïnitialiseerd met 'iets' maar niet met ""
Je moet het resultaat van deze functie nooit naar een reference schrijven.
OF niet eem "" meegeven maar een parameter:
const string& leeg;
c.get_value(start,leeg);

opgelost!
